[anchor]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
solana_predict = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"

[programs.devnet]
solana_predict = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"

[programs.mainnet]
solana_predict = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
program = "target/deploy/solana_predict.so"

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "processed"
ledger = ".anchor/test-ledger"
bind_address = "0.0.0.0"
rpc_port = 8899
websocket_port = 8900
startup_wait = 5000
shutdown_wait = 2000
limit_ledger_size = 10000
skip_serving_rpc = false
quiet = false

[build]
exclude = ["node_modules", "target", ".git"]